concrete-message: Configuration Específica entorno Des! (fichero apps/gateway-product/gateway-product.yml)

app:
  fqdn: localhost

byl:
  audit:
    enabled: false
    internal-enable: false
  ldap:
    active: false

cache:
  enable-redis: false

spring:
  profiles:
    active: ${SHORT_ENV}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  # Datasources
  datasource:
    datasource-initializer-enabled: false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: jdbc:sqlserver://svmos101036-sql.byl.local;databaseName=NAVWEB;sslProtocol=TLSv1.2;trustServerCertificate=true;
    ##url: jdbc:sqlserver://svmos107021.byl.local;databaseName=NAVPRE;sslProtocol=TLSv1.2;trustServerCertificate=true;
    username: uproductintegration
    password: '{cipher}ae4e01d1b3fc8bcd5618d8bf17fdff4949cfb853e77fbcd054b2839fcefab9f1ad7e21f3242b327083c68dcf4aa777f9'
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    poolName: HikariCP-Principal

codeunit:
  url: http://svmos107016.byl.local:7047/CENTRAL/WS/BIMBA%20Y%20LOLA/Codeunit/WSPLM
  user: srvcnavparserdev
  password: '{cipher}119d6957224f92362f15c45ba60b91681bf564d31db2453d6e6825cd60144f7fb45fc2ad5b12512f1b5008e863a4aa39'

logback:
  level:
    elastic: INFO