server:
  port: 8081

command:
  name: configuracionComandos
  commands:
    - name: ARRIVALS
      bean-name: arrivalsCommand
    - name: AUTO_APPROVED_CHANGES
      bean-name: autoApprovedChangesCommand
    - name: CROSS_SEASONS_CHANGES
      bean-name: crossSeasonsChangesCommand
    - name: NOTIFICATION
      bean-name: notificationCommand
    - name: RANKING
      bean-name: rankingCommand
    - name: SAVE_AUTO_ENTRIES
      bean-name: saveAutoEntriesCommand

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  profiles:
    active: ${SHORT_ENV}

webclient:
  max-in-memory-size: 10000000
  distribucion:
    base-path: ${services.distribucion.interna.gateway-distribucion-api-v1}
    retry-attempts: 3
    retry-time: 30
    update-size: 1000
    endpoints:
      country-arrivals: /country-arrivals/search
      country-received: /country-arrivals/received/size/search
      cross-seasons-changes: /references/cross-seasons/changes
      estimated-country-arrivals: /country-arrivals/estimated/search
      location-sales: /store-sales/location/{season}
      location-stock: /store-sales/stock/location/{season}
      superfamily-sales: /store-sales/superfamily/{season}
      superfamily-stock: /store-sales/stock/superfamily/{season}
  galgo:
    base-path: ${services.distribucion.interna.galgo-back-api-v1}
    #base-path: http://localhost:8080/galgo-back-api-v1/
    retry-attempts: 3
    retry-time: 30
    page-size: 5000
    update-size: 1000
    endpoints:
      cycles: /top-references/cycles
      cross-seasons-changes-send: /top-references/cross-seasons/changes
      estimated-entry-config: /top-references/entries/config
      get-arrivals: /top-references/arrivals/search
      intermediate-warehouse: /top-references/intermediate-warehouse
      locations: /top-store/locations
      notification-config: /notifications/top-store
      notifications:
        - url-pending: /notifications/entries/changes/pending
          url-updated: /notifications/entries/changes/updated/{seconds}
        - url-pending: /notifications/top-reference/changes/pending
          url-updated: /notifications/top-reference/changes/updated/{seconds}
        - url-pending: /notifications/top-store/changes/pending
          url-updated: /notifications/top-store/changes/updated/{seconds}
      ranking-store: /ranking/store/{season}
      ranking-superfamily: /ranking/superfamily/{season}
      references: /top-references/references/search
      ref-locks-global: /ref-locks/global
      ref-locks-references: /ref-locks
      top-com-groups: /top-commercial/groups
      top-ref-auto-approve: /top-references/changes/auto-approve
      top-ref-changes: /top-references/changes/search
      top-ref-detail: /top-references/search/{dataStatus}/detail
      top-ref-entries-detail: /top-references/entries/search/{dataStatus}
      top-ref-entries-changes: /top-references/entries/changes/search
      top-ref-entries-auto-approve: /top-references/entries/changes/auto-approve
      top-store-auto-approve: /top-store/changes/{season}/auto-approve
      top-store-changes: /top-store/changes/search/{season}
      top-store-detail: /top-store/{season}/{dataStatus}
      sales-config: /ranking/sales-config
      save-arrivals: /top-references/arrivals
      save-estimated-entries: /top-references/entries/estimated
      save-auto-entries: /top-references/entries/auto
      seasons: /seasons
      superfamilies: /top-store/superfamilies
  producto:
    page-size: 10000
    base-path: ${services.producto.interna.master-producto-api-v1}
    retry-attempts: 3
    retry-time: 30
    endpoints:
      shipment-orders-galgo: /shipment-orders/galgo