command:
  name: configuracionComandos
  commands:
    - name: RANKING
      bean-name: rankingCommand
    - name: NOTIFICATION
      bean-name: notificationCommand
    - name: ARRIVALS
      bean-name: arrivalsCommand

persistence:
  path-shipment-orders: /mnt/galgo/shipment-orders
  file-shipment-orders: Shipment_Orders_PLM.xlsx

spring:
  profiles:
    active: ${SHORT_ENV}

webclient:
  max-in-memory-size: 10000000
  distribucion:
    base-path: ${services.distribucion.interna.gateway-distribucion-api-v1}
    retry-attempts: 3
    retry-time: 30
    update-size: 1000
    endpoints:
      location-sales: /store-sales/location/{season}
      location-stock: /store-sales/stock/location/{season}
      superfamily-sales: /store-sales/superfamily/{season}
      superfamily-stock: /store-sales/stock/superfamily/{season}
  galgo:
    base-path: ${services.distribucion.interna.galgo-back-api-v1}
    retry-attempts: 3
    retry-time: 30
    page-size: 5000
    endpoints:
      locations: /top-store/locations
      notifications:
        - url-pending: /notifications/top-reference/changes/pending
          url-updated: /notifications/top-reference/changes/updated/{seconds}
        - url-pending: /notifications/top-store/changes/pending
          url-updated: /notifications/top-store/changes/updated/{seconds}
      ranking-store: /ranking/store/{season}
      ranking-superfamily: /ranking/superfamily/{season}
      sales-config: /ranking/sales-config
      save-arrivals: /top-references/arrivals
      seasons: /seasons
      superfamilies: /top-store/superfamilies
      get-arrivals:
      save-estimated-entries: