command:
  name: configuracionComandos
  commands:
    - name: ARRIVALS
      bean-name: arrivalsCommand
    - name: CROSS_SEASONS_CHANGES
      bean-name: crossSeasonsChangesCommand
    - name: ESTIMATION
      bean-name: estimationCommand
    - name: NOTIFICATION
      bean-name: notificationCommand
    - name: RANKING
      bean-name: rankingCommand

persistence:
  path-shipment-orders: /mnt/galgo/shipment-orders
  file-shipment-orders: Shipment_Orders_PLM.xlsx

spring:
  profiles:
    active: ${SHORT_ENV}

webclient:
  max-in-memory-size: 10000000
  distribucion:
    base-path: ${services.distribucion.interna.gateway-distribucion-api-v1}
    retry-attempts: 3
    retry-time: 30
    update-size: 1000
    endpoints:
      country-arrivals: /country-arrivals/search
      country-received: /country-arrivals/received/size/search
      cross-seasons-changes: /references/cross-seasons/changes
      estimated-country-arrivals: /country-arrivals/estimated/search
      location-sales: /store-sales/location/{season}
      location-stock: /store-sales/stock/location/{season}
      superfamily-sales: /store-sales/superfamily/{season}
      superfamily-stock: /store-sales/stock/superfamily/{season}
  galgo:
    base-path: ${services.distribucion.interna.galgo-back-api-v1}
    retry-attempts: 3
    retry-time: 30
    page-size: 5000
    update-size: 1000
    endpoints:
      cycles: /top-references/cycles
      estimated-entry-config: /top-references/entries/config
      get-arrivals: /top-references/arrivals/search
      intermediate-warehouse: /top-references/intermediate-warehouse
      locations: /top-store/locations
      notification-config: /notifications/top-store
      notifications:
        - url-pending: /notifications/entries/changes/pending
          url-updated: /notifications/entries/changes/updated/{seconds}
        - url-pending: /notifications/top-reference/changes/pending
          url-updated: /notifications/top-reference/changes/updated/{seconds}
        - url-pending: /notifications/top-store/changes/pending
          url-updated: /notifications/top-store/changes/updated/{seconds}
      ranking-store: /ranking/store/{season}
      ranking-superfamily: /ranking/superfamily/{season}
      references: /top-references/references/search
      sales-config: /ranking/sales-config
      save-arrivals: /top-references/arrivals
      save-estimated-entries: /top-references/entries/estimated
      seasons: /seasons
      superfamilies: /top-store/superfamilies