byl:
  encryption:
    enabled: true
    public: '{cipher}f27aeec445035e71a89385db8c951a07ec56085ccceed29f80fb484240c18916d7f686f0edb97d2c21d86002752f780d4f351841e8eee2208d0961e39346c23b75ba8ab30455323819e8546dabbcf383da151d0d7df8793824550ad53555e1851b643717c7220be8c1c556b6ef9dddf0e6611383d8cb8f625af8f269569f5600b668bbc8ef15e585b85aabb3bf0fb8ab0e87ab03a49b395d0e3a3192e3a8cf3ab40cf3503af353fb271cfa519fd44a7d'

command:
  name: configuracionComandos
  commands:
    - name: SYNCH_CATALOG
      bean-name: synchCatalogCommand
    - name: FULL_CATALOG
      bean-name: fullCatalogCommand

project:
  mq:
    host: 'bylla-dev-1-mq.oms.supply-chain.ibm.com'
    port: 15443
    queue-manager: OM_QMGR
    channel: SYSTEM.TLS.SVRCONN
    username: mqm
    password: xxxxxx
    receive-timeout: 20000
    delivery-timeout: 20000
    cypher: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    queue: BYL_DOM_IN_CATALOG_Q
  # API distribucion
  distribucion:
    api:
      host: ${services.distribucion.interna.gateway-distribucion-api-v1}
      endpoints:
        items: /items/item-variants
        catalog-by-season: /items/catalog-by-season
  num-items-per-message: 1

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

webclient:
  max-in-memory-size: 10000000
  distribucion:
    retry-attemps: 7
    retry-time: 60
    base-path: ${services.distribucion.interna.gateway-distribucion-api-v1}
    services:
      catalog-by-season: /items/catalog-by-season
      items: /items/item-variants
  oms:
    retry-attemps: 5
    retry-time: 10
    tenant: '{cipher}83d89f69899cc742fef51bb36e1561856f2195af82f5c16493b8c999464ffd6c'
    oauth:
      client-id: VX70AqA4MGuFfB530DmfCNr9QokhdfFM
      client-secret: '{cipher}58025dc0788227423810cfc69e3a749ae604548378eaab6efcf4c1b57f8340d97cbdb9b53f4fc384cd9f90176c5ce94dce8f608a39ede094ddf64b813bbbf118'
    base-path:
      catalog: https://api.watsoncommerce.ibm.com/catalog/${webclient.oms.tenant}/v1
      configuration: https://api.watsoncommerce.ibm.com/configuration/${webclient.oms.tenant}/v1
    services:
      items: /items
      oauth: /oauth2/token