#-------------------------
# NET core:
#-------------------------

ApplicationInsights:
  InstrumentationKey: __application_insights_instrumentation_key__
AllowedHosts: "*"

# Identity:
Identity:
  MetadataAddress: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
  Issuer: https://sts.windows.net/ad3e5ddd-b802-46fa-a45e-1ebda6f783a8/

#logging
Logging:
  LogLevel:
    Default: Information
    System: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information
    Microsoft.AspNetCore: Warning
    Microsoft.AspNetCore.Hosting.Diagnostics: None

Path_Metrics: /actuator/prometheus

# Serilog
Serilog:
  Enrich:
    - FromLogContext
    - WithExceptionDetails
    - WithProcessId
    - WithProcessName
    - WithThreadId
    - WithThreadName
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.AspNetCore.Hosting.Diagnostics: Error
      Microsoft.AspNetCore.Routing.EndpointMiddleware: Error
  Using:
    - Serilog.Sinks.ElasticSearch
  WriteTo:
    - Name: Elasticsearch
      Args:
        autoRegisterTemplate: true
        autoRegisterTemplateVersion: ESv7
        batchAction: Create
        connectionTimeout: 30000
        deadLetterIndexName: deadletter-%SHORT_ENV%-{0:yyyy.MM}
        formatter: Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
        indexFormat: app-log-%SHORT_ENV%-{0:yyyy.MM.dd}
        inlineFields: true
        nodeUris: "{cipher}ab3bb46f344c45b1b78e354a8d647f2b150a97aff64e3d9156bd672c073b31e39353621e31c7e25f8008d986f60d7816c880deab8e79d157e2daea62c823a3531906a4778745e6e81fcc16842a29261b"
        queueSizeLimit: "104857600"
        renderMessage: false
      restrictedToMinimumLevel: Information


#-------------------------
# End NET core:
#-------------------------

#-------------------------
# Java:
#-------------------------

app:
  consumer:
    enabled: false
  producer:
    enabled: false

  version: ${project.version:0.0.0}
  full-max-page-size: 50000

azure:
  sb:
    endpoint: sb://byl-core-dev.servicebus.windows.net/

byl:
  addTraceInApiException: true
  audit:
    enabled: false
    internal-enable: false
  auto-health: false
  datasource-erp:
    enabled: false
  datasource-primary:
    enabled: false
  encryption:
    enabled: false
    private: '{cipher}540423e80bc80be33e02d144505e3c27340ec1eea67c0e747d89871a5cdf0269fa716f60b8817492135e2718868472f2f601d928522d47fad63e8f07170d98984e5094313e151f8281c230387d112ff8aee6447a510ee30dc824421a6a99263737a6ebdad690d13572de6ab760c15cd4e24991cfd8eebc9b4e4fe3110fb3e05a35c0b933d196702cf7204f87db0f5b4ca06e11f422410536260f662ebb4e6016a2e66fdd8fe0efb541242277dfc304c40b6c0dc99cfa6a09d16ca9c030ad3be4970a7c9c5eb817427f56bd8e6bf30cff05d93a46a6079e33b97850ec38901c9a14a239051c887e8627b8f1c0a251c8da2b17e74804e7f7b216a20e68f241a1e99f975ffacd3c07c061f55d9ac05ed21c6071e070a668a1536a18ffdb0da54eb1f6fc0ea4aa958a62ca479425db07b957c515486610e17968cb28c0f4dfb53619cc236936f6dad50d1feba3af134cef1c526b787a4d921fd2c3f29f1695869c5fe6a8e6b02c6d39abb2cee868c2b64fde2700fc84e68b340201a63b622f68df782d398d930a1e6849b46992911f85cd1d0c2d8dc8742b6f8a66b29980cdf70dcf0164b6a638690ca819e35f07f9f367d08f04f1996eb7e44c72fcbb2546fd0f5ede58f8a473ed3c617d0ad9e7a4213400352135bf5614b13a57b365972cb76177eeb0fab8bb87e30d0bd0ac18da196873e5a7efb9c901d9d0ec9a3b864cb752d68c2881a007f8d840bac32e82a8f97189dc588bd046ccb4c78035e5b7419bdca1ac66fb6c0db40202759696169d075585'
    public: '{cipher}f27aeec445035e71a89385db8c951a07ec56085ccceed29f80fb484240c18916d7f686f0edb97d2c21d86002752f780d4f351841e8eee2208d0961e39346c23b75ba8ab30455323819e8546dabbcf383da151d0d7df8793824550ad53555e1851b643717c7220be8c1c556b6ef9dddf0e6611383d8cb8f625af8f269569f5600b668bbc8ef15e585b85aabb3bf0fb8ab0e87ab03a49b395d0e3a3192e3a8cf3ab40cf3503af353fb271cfa519fd44a7d'
  excludeAuditRest: '/swagger,/api-docs,/actuator,/swagger-ui,/swagger-resources,/v3,/health'
  isRestAuditable: true
  ldap:
    active: false
  sftp:
    host: sftp-service.dev-arqsw.svc.cluster.local
    port: 2222
    user: docker
    password: "{cipher}145dc2e538c4d305dbda92705a79c82b03fbaedaed7deb76d411c6541751db10"

cache:
  # Tiempo de cache en sg.
  caches-ttl:
    cache-week: 604800
    cache-day: 86400
    cache-hour: 3600
  compartida: false
  default-ttl: 86400
  enable-redis: false
  host: core-byl-dev-redis.redis.cache.windows.net
  key-prefix: '${spring.application.name}'
  password: "{cipher}a735e0cd2a5dc30957532058d1dbe0c3b8831693ebfbd4386d470bac3abd044835f34b54886f9ff9df74595719834c0b66f8a4297fe25b9ac55c6aa0b31f208a"
  port: 6380
  ssl: true
  task-force: ${TASK_FORCE}
  use-key-prefix: true

# Elasticsearch props
elasticsearch:
  api-key: "{cipher}d062acfa560566d37b1ca368e0f656f2c4e9b772a4327c7e5a32a7b655d923af8995cb6e3b7a61a42c41706b591e2308070e4750385b86be2fa7840da1600cc94a124cb7c87fbd5548a3fa778bdafa80"
  host: 10.80.54.4
  host-on-premise: 10.20.101.47
  authorization:
    type: Basic
    password: "{cipher}0329d666e5a4cdb9964b1f7b71722c4f1d0a398d1716db14353d477bdcc4d5a4caaa45ab8212a7005472faebf890945cca5687c87a5f099c277d238fad67213ebba0acf35021283ddf7e5ea903278fc0"
  timeout: 30000
  log-level: INFO

# Para exponer los endpoints de actuator
management:
  endpoint:
    env:
      enabled: true
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      cors:
        allowed-methods: "GET,POST"
        allowed-origins: "http://localhost"
      exposure:
        include: health,info,prometheus,env
  health:
    defaults:
      enabled: false
    probes:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
      health:
        time-export: 60000
    web:
      server:
        request:
          autotime:
            enabled: true

persistence:
  path: "/mnt/persistent"

plm-config:
  enabled: false

# Datos del server
server:
  port: 8080
  servlet:
    context-path: "/${spring.application.name}-api-v${app.version_url}"
  ssl:
    enabled: false

# Datos de spring
spring:
  banner:
    location: classpath:/banner.txt
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  jpa:
    open-in-view: false
  mail:
    host: correoweb.bimbaylola.com
    port: 587
    username: srvcmailsml@bimbaylola.com
    password: '{cipher}8961f6abd28d3ad1dd88c1561b7c247961989c18b3c212f29eefa62e693908d338ec393231cd0531240a42efcffa815f'
    from: srvcmailsml@bimbaylola.com
  main:
    banner-mode: console
  output:
    ansi:
      enabled: DETECT
  profiles:
    active: ${SHORT_ENV}
  # Seguridad
  security:
    enable-csrf: false
    enabled: false
    basic:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    displayOperationId: true
    operationsSorter: alpha
    path: /swagger/index.html
    tagsSorter: alpha

#-------------------------
# End Java:
#-------------------------

services:
  arqsw:
    interna:
      demo-api-v1: http://desazure.byl.local/demo-api-v1
      fake-orders-api-v1: http://desazure.byl.local/fake-orders-api-v1
      fake-orders-front-v1: http://desazure.byl.local/fake-orders-front-v1
      sccs: http://desazure.byl.local/sccs
      master-api-v1: http://desazure.byl.local/master-api-v1
  distribucion:
    externa:
      gateway-distribucion-api-v1: http://desazure.byl.local/gateway-distribucion-api-v1
      galgo-front-v1: http://desazure.byl.local/galgo-front-v1
    interna:
      galgo-back-api-v1: http://desazure.byl.local/galgo-back-api-v1
      galgo-front-v1: http://desazure.byl.local/galgo-front-v1
      gateway-distribucion-api-v1: http://desazure.byl.local/gateway-distribucion-api-v1
      gateway-oms-logistica-api-v1: http://desazure.byl.local/gateway-oms-logistica-api-v1
      gateway-oms-api-v1: http://desazure.byl.local/gateway-oms-api-v1
  expansion:
    interna:
      gateway-mkpl-api-v1: http://preazure.byl.local/gateway-marketplaces-api-v1
      mkpl-services-api-v1: http://preazure.byl.local/mkpl-services-api-v1
  marketing:
    interna:
      gateway-helpdesk-atc-api-v1: http://desazure.byl.local/gateway-helpdesk-atc-api-v1
  producto:
    interna:
      gateway-product-api-v1: http://desazure.byl.local/gateway-product-api-v1
      gateway-plm-api-v1: http://desazure.byl.local/gateway-plm-api-v1
      master-producto-api-v1: http://desazure.byl.local/master-producto-api-v1
  tiendas:
    interna:
      cards-api-v1: http://desazure.byl.local/cards-api-v1
      clickandcollect-api-v1: http://desazure.byl.local/clickandcollect-api-v1
      gateway-tiendas-2-api-v1: http://desazure.byl.local/gateway-tiendas-2-api-v1
      gateway-tiendas-api-v1: http://desazure.byl.local/gateway-tiendas-api-v1