#-------------------------
# NET core:
#-------------------------

ApplicationInsights:
  InstrumentationKey: __application_insights_instrumentation_key__
AllowedHosts: "*"

# Identity:
Identity:
  MetadataAddress: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
  Issuer: https://sts.windows.net/ad3e5ddd-b802-46fa-a45e-1ebda6f783a8/

#logging
Logging:
  LogLevel:
    Default: Information
    System: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information
    Microsoft.AspNetCore: Warning
    Microsoft.AspNetCore.Hosting.Diagnostics: None

Path_Metrics: /actuator/prometheus

# Serilog
Serilog:
  Enrich:
    - FromLogContext
    - WithExceptionDetails
    - WithProcessId
    - WithProcessName
    - WithThreadId
    - WithThreadName
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.AspNetCore.Hosting.Diagnostics: Error
      Microsoft.AspNetCore.Routing.EndpointMiddleware: Error
  Using:
    - Serilog.Sinks.ElasticSearch
  WriteTo:
    - Name: Elasticsearch
      Args:
        autoRegisterTemplate: true
        autoRegisterTemplateVersion: ESv7
        batchAction: Create
        connectionTimeout: 30000
        deadLetterIndexName: deadletter-%SHORT_ENV%-{0:yyyy.MM}
        formatter: Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
        indexFormat: app-log-%SHORT_ENV%-{0:yyyy.MM.dd}
        inlineFields: true
        nodeUris: "{cipher}ab3bb46f344c45b1b78e354a8d647f2b150a97aff64e3d9156bd672c073b31e39353621e31c7e25f8008d986f60d7816c880deab8e79d157e2daea62c823a3531906a4778745e6e81fcc16842a29261b"
        queueSizeLimit: "104857600"
        renderMessage: false
      restrictedToMinimumLevel: Information


#-------------------------
# End NET core:
#-------------------------

#-------------------------
# Java:
#-------------------------

app:
  consumer:
    enabled: false
  producer:
    enabled: false

  version: ${project.version:0.0.0}
  full-max-page-size: 50000



byl:
  addTraceInApiException: true
  audit:
    enabled: false
    internal-enable: false
  auto-health: false
  datasource-erp:
    enabled: false
  datasource-primary:
    enabled: false
  encryption:
    enabled: false
  excludeAuditRest: '/swagger,/api-docs,/actuator,/swagger-ui,/swagger-resources,/v3,/health'
  isRestAuditable: true
  ldap:
    active: false
  sftp:
    host: sftp-service.dev-arqsw.svc.cluster.local
    port: 2222
    user: docker
    password: "{cipher}145dc2e538c4d305dbda92705a79c82b03fbaedaed7deb76d411c6541751db10"

cache:
  # Tiempo de cache en sg.
  caches-ttl:
    cache-week: 604800
    cache-day: 86400
    cache-hour: 3600
  compartida: false
  default-ttl: 86400
  enable-redis: false
  host: core-byl-dev-redis.redis.cache.windows.net
  key-prefix: '${spring.application.name}'
  password: "{cipher}a735e0cd2a5dc30957532058d1dbe0c3b8831693ebfbd4386d470bac3abd044835f34b54886f9ff9df74595719834c0b66f8a4297fe25b9ac55c6aa0b31f208a"
  port: 6380
  ssl: true
  task-force: ${TASK_FORCE}
  use-key-prefix: true

# Elasticsearch props
elasticsearch:
  host: 10.80.54.4
  host-on-premise: 10.20.101.47
  authorization:
    type: Basic
    password: "{cipher}0329d666e5a4cdb9964b1f7b71722c4f1d0a398d1716db14353d477bdcc4d5a4caaa45ab8212a7005472faebf890945cca5687c87a5f099c277d238fad67213ebba0acf35021283ddf7e5ea903278fc0"
  timeout: 30000
  log-level: INFO

# Para exponer los endpoints de actuator
management:
  endpoint:
    env:
      enabled: true
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      cors:
        allowed-methods: "GET,POST"
        allowed-origins: "http://localhost"
      exposure:
        include: health,info,prometheus,env
  health:
    defaults:
      enabled: false
    probes:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
      health:
        time-export: 60000
    web:
      server:
        request:
          autotime:
            enabled: true

persistence:
  path: "/mnt/persistent"

plm-config:
  enabled: false

# Datos del server
server:
  port: 8080
  servlet:
    context-path: "/${spring.application.name}-api-v${app.version_url}"
  ssl:
    enabled: false

# Datos de spring
spring:
  banner:
    location: classpath:/banner.txt
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  jpa:
    open-in-view: false
  main:
    banner-mode: console
  output:
    ansi:
      enabled: DETECT
  profiles:
    active: des
  # Seguridad
  security:
    enable-csrf: false
    enabled: false
    basic:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    displayOperationId: true
    operationsSorter: alpha
    path: /swagger/index.html
    tagsSorter: alpha

#-------------------------
# End Java:
#-------------------------

services:
  arqsw:
    interna:
      demo-api-v1: http://desazure.byl.local/demo-api-v1
      fake-orders-api-v1: http://desazure.byl.local/fake-orders-api-v1
      fake-orders-front-v1: http://desazure.byl.local/fake-orders-front-v1
      sccs: http://desazure.byl.local/sccs
      #master-api-v1: http://desazure.byl.local/master-api-v1
      master-api-v1: localhost:8080/master-api-v1
  distribucion:
    interna:
      galgo-back-api-v1: http://desazure.byl.local/galgo-back-api-v1
      galgo-front-v1: http://desazure.byl.local/galgo-front-v1
      gateway-distribucion-api-v1: http://desazure.byl.local/gateway-distribucion-api-v1
      gateway-oms-logistica-api-v1: http://desazure.byl.local/gateway-oms-logistica-api-v1
  marketing:
    interna:
      gateway-helpdesk-atc-api-v1: http://desazure.byl.local/gateway-helpdesk-atc-api-v1
  producto:
    interna:
      gateway-product-api-v1: http://desazure.byl.local/gateway-product-api-v1
  tiendas:
    interna:
      cards-api-v1: http://desazure.byl.local/cards-api-v1
      clickandcollect-api-v1: http://desazure.byl.local/clickandcollect-api-v1
      gateway-tiendas-2-api-v1: http://desazure.byl.local/gateway-tiendas-2-api-v1
      gateway-tiendas-api-v1: http://desazure.byl.local/gateway-tiendas-api-v1