byl:
  audit:
    enabled: false
    internal-enable: false
  ldap:
    active: false
cache:
  enable-redis: true
spring:
  profiles:
    active: ${SHORT_ENV}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

services:
  export-pagesize: 500
  supply-chain:
    user: 'admin'
    pass: '{cipher}0dee57ce5dd59a09bcf13f438dc6c396f5eacf97110e4a00c4656f052f7d521e'
    base-path: https://bylla-dev-1.oms.supply-chain.ibm.com/smcfs/restapi/invoke
    endpoints:
      get-page: /getPage
      order-line-details: /getOrderLineDetails
    pageable-endpoints:
      item-list: getItemList
      order-line-list: getOrderLineList
  oms:
    tenant: '{cipher}83d89f69899cc742fef51bb36e1561856f2195af82f5c16493b8c999464ffd6c'
    oauth:
      client-id: '{cipher}9f648580f8bf05b29bad159e6b118417ed03cd0d2ed6f2a97edcbeab6b34a28bcbc65d79664b5132fae8d25c8a41306825084da72d3672f5c3513e3890a32cff'
      client-secret: '{cipher}58025dc0788227423810cfc69e3a749ae604548378eaab6efcf4c1b57f8340d97cbdb9b53f4fc384cd9f90176c5ce94dce8f608a39ede094ddf64b813bbbf118'
    base-path: https://api.watsoncommerce.ibm.com/inventory/${services.oms.tenant}/v1
    endpoints:
      oauth: /oauth2/token
      availability-network: /availability/network
      distribution-groups: /configuration/distributionGroups


azure:
  storage:
    enabled: false
    accounts:
      distribucion:
        account-id: distribucion
        tables:
          replenishment-config: ReplenishmentConfig
          replenishment-audit: ReplenishmentAudit
          top-commercial: TopCommercial
          top-commercial-hist: HistTopCommercial
          batch-status: BatchStatus

    config:
      accounts:
        distribucion:
          name: tskfdistribuciondev
          key: 20XF+PYutl64nWLO3Rgh3tgN6NQhIlHOUrXccA/E5/8GWWBAWfpWVA00hgLBvxaVTeUJ55o8vqQb+AStMYqLxA==

security:
  enable-csrf: false
  jwk:
    provider:
      url: https://login.microsoftonline.com/common/discovery/keys
    app:
      aud: api://a2089459-7f1f-4291-a416-6cf367ee3598
      appid: a2089459-7f1f-4291-a416-6cf367ee3598


config:
  dependencies:
    batch:
      on-demand-replenishment:
        - batch: oms-replenishment
          command: PLANNED

app:
  azure:
    service-bus:
      distribucion:
        endpoint: sb://byl-core-dev.servicebus.windows.net/
        sharedAccessKeyName: oms-erp
        sharedAccessKey: axSOs+H3JbmTcmS4NmGJouCU2CiMRWUvS+ASbNfTIjo=
        entityPath: distribucion.oms-erp
        labels:
          on-demand-replenishment: onDemandReplenishment
 