app:
  fqdn: localhost
byl:
  audit:
    enabled: false
    internal-enable: false
  ldap:
    active: false
  datasource-primary:
    enabled: false


cache:
  enable-redis: true
spring:
  profiles:
    active: ${SHORT_ENV}


  # Datasources
  datasource:
    datasource-initializer-enabled: false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: jdbc:sqlserver://svmos101036-sql.byl.local;databaseName=NAVWEB;sslProtocol=TLSv1.2;trustServerCertificate=true;
    username: uomsdev
    password: '{cipher}47b50a89a885ad24ef46595a55cd5c88c6b874aae4f06e003b8137486bfbeeec'
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    poolName: HikariCP-Principal

services:
  export-pagesize: 5000
  supply-chain:
    user: 'admin'
    pass: 'password'
    base-path: https://bylla-dev-1.oms.supply-chain.ibm.com/smcfs/restapi/invoke
    endpoints:
      get-page: /getPage
      order-line-details: /getOrderLineDetails
    pageable-endpoints:
      item-list: getItemList
      order-line-list: getOrderLineList

  oms:
    tenant: '{cipher}83d89f69899cc742fef51bb36e1561856f2195af82f5c16493b8c999464ffd6c'
    oauth:
      client-id: '{cipher}9f648580f8bf05b29bad159e6b118417ed03cd0d2ed6f2a97edcbeab6b34a28bcbc65d79664b5132fae8d25c8a41306825084da72d3672f5c3513e3890a32cff'
      client-secret: '{cipher}58025dc0788227423810cfc69e3a749ae604548378eaab6efcf4c1b57f8340d97cbdb9b53f4fc384cd9f90176c5ce94dce8f608a39ede094ddf64b813bbbf118'
    base-path: https://api.watsoncommerce.ibm.com/inventory/${services.oms.tenant}/v1
    endpoints:
      oauth: /oauth2/token
      availability-network: /availability/network
      distribution-groups: /configuration/distributionGroups


azure:
  storage:
    enabled: false
    accounts:
      distribucion:
        account-id: distribucion
        tables:
          restocking-config: DevRestockingConfig

    config:
      accounts:
        distribucion:
          name: tskfdistribuciondev
          key: 20XF+PYutl64nWLO3Rgh3tgN6NQhIlHOUrXccA/E5/8GWWBAWfpWVA00hgLBvxaVTeUJ55o8vqQb+AStMYqLxA==
