byl:
  audit:
    enabled: false
    internal-enable: false
  ldap:
    active: false
cache:
  enable-redis: true
spring:
  profiles:
    active: ${SHORT_ENV}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    datasource-initializer-enabled: false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      driverClassName: com.mysql.cj.jdbc.Driver
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: jdbc:mysql://azdistributiondesmysql.mysql.database.azure.com:3306/galgo-des?useSSL=true&clientCertificateKeyStoreUrl=file:C:/byl-security/mysql.jks&clientCertificateKeyStorePassword=passw0rd
    username: galgo
    password: XBnt57eLPohDGPX
    driverClassName: com.mysql.cj.jdbc.Driver
    poolName: HikariCP-Principal
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

persistence:
  path-shipment-orders: /mnt/galgo/shipment-orders
  file-shipment-orders: Shipment_Orders_PLM.xlsx


services:
  export-pagesize: 5000
  supply-chain:
    user: 'admin'
    pass: '{cipher}0dee57ce5dd59a09bcf13f438dc6c396f5eacf97110e4a00c4656f052f7d521e'
    base-path: https://bylla-preprod-1.oms.supply-chain.ibm.com/smcfs/restapi/invoke
    endpoints:
      get-page: /getPage
      order-line-details: /getOrderLineDetails
    pageable-endpoints:
      item-list: getItemList
      order-line-list: getOrderLineList
  oms:
    tenant: '{cipher}b86ce348036e0e9e086628a6ac6e0b400d052b0c36b19fe5f3274706edee36ce'
    oauth:
      client-id: '{cipher}49e0043c7a53da5e950ee19df0c2c604c6f7ac95c5e88b89143a24ae338c518f4ed75322c8668222dd727b21198be26a722a788b1ebeaf9f3a714f38351815f9'
      client-secret: '{cipher}cf533bf526895bc3859180efe3580edf646b22b3bc4bbc119ef2771be1ee9389ca1fab63d9c29a46b20f8eb1fd1fa3868514fb2846ae842f4af148d9ef892836'
    base-path: https://api.watsoncommerce.ibm.com/inventory/${services.oms.tenant}
    endpoints:
      oauth: /v1/oauth2/token
      availability-network: /v2/availability/network
      distribution-groups: /v1/configuration/distributionGroups

azure:
  storage:
    enabled: false
    accounts:
      distribucion:
        account-id: distribucion
        tables:
          batch-status: BatchStatus
          replenishment-audit: ReplenishmentAudit
          replenishment-config: ReplenishmentConfig
    config:
      accounts:
        distribucion:
          name: tskfdistribuciondev
          key: '{cipher}f15852849941c1ac3595381f352973e6b059c2288a824c11b3c0655c58d944174b514059a3a4fd11a5c41d745710b522aec8c4b7429e7a6840063e0ba34bf9dbd8761910c1e9f37e05982181b5782b89235b7fbf652f82877a8010b972611b565e57795234362dc47b514f0fa3eaac0f'

security:
  enable-csrf: false
  jwk:
    provider:
      url: https://login.microsoftonline.com/common/discovery/keys
    app:
      aud: '{cipher}9cd897ede4cb38f2fc2acdee083fb11fb50fec528b23972e38053703064ebb01297337f99927f762b742257520783e76f136d321182f482043dddbb3eb1003fd'
      appid: '{cipher}6088cd8bf816b547bc461e5345e48f13c7cc47cc01196f85d636ffb4a10aa702f705a77b5a703625cf9c138f87a22ab31dff00b31af8514b7b00d8259cbd0453'

config:
  dependencies:
    batch:
      on-demand-replenishment:
        - batch: oms-replenishment
          command: PLANNED

app:
  azure:
    service-bus:
      distribucion:
        endpoint: sb://byl-core-dev.servicebus.windows.net/
        sharedAccessKeyName: oms-erp
        sharedAccessKey: '{cipher}f21808ed3369c07931015f286eec69684ea630a65a58abd137da803c3cc2e0d4cb77239b9d9fdab41bf9c945480121dace2cca2cb78beae2bd5aad4f86b4dfe8'
        entityPath: distribucion.oms-erp
        labels:
          on-demand-replenishment: onDemandReplenishment
  notification:
    galgo-front:
      base-path: http://desazure.byl.local/galgo-front-v1
      pages:
        top-reference-audit: /reference/audit
        top-store-audit: /store/audit

webclient:
  max-in-memory-size: 10000000
  distribucion:
    base-path: ${services.distribucion.interna.gateway-distribucion-api-v1}
    endpoints:
      superfamilies: /superfamilies
      references: /references/{season}
  master:
    base-path: ${services.arqsw.interna.master-api-v1}
    endpoints:
      locations: /locations

mail:
  host: smtp-mail.outlook.com
  port: 587
  username: develop.byl@outlook.com
  password: Dev10101010
  from: develop.byl@outlook.com