command:
  name: configuracionComandos
  commands:
    - name: SYNCH_ORDERS
      bean-name: synchOrdersCommand
    - name: CLEAN_ORDERS
      bean-name: cleanOrdersCommand

process:
  config:
    persistence:
      max-days: 7

azure:
  storage:
    accounts:
      global-persistence:
        account-id: global-persistence
        tables:
          order-queue-audit: DevOmsSynchOrders
    config:
      accounts:
        global-persistence:
          name: globalpersistence
          key: '{cipher}633140e53ebeb3f501200f518c6904ba30e33d829f971c9ad9e12f732bdfad3ed00831f2a9abdc7feeec3805b33787f3cf2aa80b04e0ed0c94beb7123ab458491e2e071355328fb1035095f435d082858b6f872127982c9788fbc0e38d1c8a797130ea2b15ff13a907269d9f8bc95970'

spring:
  profiles:
    active: ${SHORT_ENV}

webclient:
  distribucion:
    base-path: http://desazure.byl.local/gateway-distribucion-api-v1
    services:
      create-order: /order/create
      confirm-shipment: /order/confirm-shipment

project:
  mq:
    host: 'bylla-dev-1-mq.oms.supply-chain.ibm.com'
    port: 15443
    queue-manager: OM_QMGR
    channel: SYSTEM.TLS.SVRCONN
    receive-timeout: 20000
    cypher: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    queue:
      create-order: BYL_DOM_OUT_RELEASE
      confirm-shipment: BYL_STORE_CONFIRM_SHIP_OUT
