command:
  name: configuracionComandos
  commands:
    - name: SYNCH_ORDERS
      bean-name: synchOrdersCommand
    - name: CLEAN_ORDERS
      bean-name: cleanOrdersCommand

process:
  config:
    persistence:
      max-days: 7

azure:
  sb:
    topics:
      service-to-central:
        keyName: service-to-central
        key: '{cipher}4f745fcb6ecd6dd92d105f1faf0cd5c930a1733a3bdce0bd31fa78a5dbaae59c160565b26bb28696c50645a15358402c3e0a2039e2c1c0d0f6805777d315b46a'
        topic: distribucion.service-to-central
        labels:
          create-order: createOrder
          confirm-shipment: confirmShipment
  storage:
    accounts:
      distribucion:
        account-id: distribucion
        tables:
          order-queue-audit: OmsSynchOrders
    config:
      accounts:
        distribucion:
          name: tskfdistribuciondev
          key: '{cipher}55d62789a2981eedb4eb0959bb97cf5844ee24e9b21f076ab2ba7609a6af940b0c6d0696fdc5a14f51ec21e9ba6766757bf3e1cca4b8d5c97e7370f103f6b49b88e90cf54238ba4a4ad48a4bc5d96c1643dc2995d5db92071677d2d84f83e07213b0c27eccc2080ee7354f974d1867ba'

spring:
  profiles:
    active: ${SHORT_ENV}

webclient:
  distribucion:
    base-path: http://desazure.byl.local/gateway-distribucion-api-v1
    services:
      create-order: /order/create
      confirm-shipment: /order/confirm-shipment

project:
  mq:
    host: 'bylla-dev-1-mq.oms.supply-chain.ibm.com'
    port: 15443
    queue-manager: OM_QMGR
    channel: SYSTEM.TLS.SVRCONN
    receive-timeout: 20000
    cypher: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    queue:
      create-order: BYL_DOM_OUT_RELEASE
      confirm-shipment: BYL_STORE_CONFIRM_SHIP_OUT
