process:
  config:
    persistence-file-path: /mnt/persistent/${spring.application.name}
    
spring:
  profiles:
    active: ${SHORT_ENV}    

webclient:
  distribucion:
    base-path: http://desazure.byl.local/gateway-distribucion-api-v1
    services:
      create-order: /order/create

project:
  mq:
    host: 'bylla-dev-1-mq.oms.supply-chain.ibm.com'
    port: 15443
    queue-manager: OM_QMGR
    channel: SYSTEM.TLS.SVRCONN
    receive-timeout: 20000
    cypher: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    queue: BYL_DOM_OUT_RELEASE
