app:
  fqdn: localhost

byl:
  audit:
    enabled: false
    internal-enable: false
  ldap:
    active: false

spring:
  profiles:
    active: ${SHORT_ENV}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

webclient:
  max-in-memory-size: 10000000
  retry-attemps: 3
  retry-time: 10
  mtec:
    base-path: https://desonprem.byl.local/byl-mtec-core-manifest-application/api/rest
    services:
      add-manifest: /manifest/addManifest