server:
  port: 8081

app:
  fqdn: localhost

byl:
  audit:
    enabled: false
    internal-enable: false
  ldap:
    active: false

spring:
  profiles:
    active: ${SHORT_ENV}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

webclient:
  max-in-memory-size: 10000000
  retry-attemps: 3
  retry-time: 10
  mtec:
    manifest:
      base-path: http://desonprem.byl.local/tms-core-manifest-api-v1/api/rest
      services:
        add-manifest: /manifest/addManifest
    order:
      base-path: http://desonprem.byl.local/tms-core-order-api-v1/api/rest
      services:
        add-order: /order/addOrder
        modify-order: /order/modifyOrder
  tiendas:
    base-path: ${services.arqsw.interna.master-api-v1}
    services:
      get-location: /locations/{location}

azure:
  storage:
    enabled: false
    accounts:
      oms-logistica:
        account-id: oms-logistica
        tables:
          companies: Empresas
    config:
      accounts:
        oms-logistica:
          name: tskfdistribuciondev
          key: '{cipher}55d62789a2981eedb4eb0959bb97cf5844ee24e9b21f076ab2ba7609a6af940b0c6d0696fdc5a14f51ec21e9ba6766757bf3e1cca4b8d5c97e7370f103f6b49b88e90cf54238ba4a4ad48a4bc5d96c1643dc2995d5db92071677d2d84f83e07213b0c27eccc2080ee7354f974d1867ba'

cache:
  enable-redis: true
  # Tiempo de cache en sg.
  caches-ttl:
    shipment-code: 345600

click-and-collect:
  courier-code: INTERNO
  courier-service-code: GENERICO


languages:
  manifest-pdf-labels:
    ESP:
      source: Origen
      carrier: Transportista
      date-and-time: Fecha y hora
      customer: CLIENTE
      total-orders: TOTAL PEDIDOS
      total-packages: TOTAL BULTOS
      total-weight: PESO TOTAL
      order-no: Nº PEDIDO
      carriers-signature: Firma del transportista
      store-signature: Firma de la tienda
    ENU:
      source: Source
      carrier: Carrier
      date-and-time: Date and Time
      customer: CUSTOMER
      total-orders: TOTAL ORDERS
      total-packages: TOTAL PACKAGES
      total-weight: TOTAL WEIGHT
      order-no: ORDER NO.
      carriers-signature: Carrier's signature
      store-signature: Store signature




