app:
  code-unit-config:
    actions:
      - name: salesPrice
        dto-name: GetSalesPriceDto
        action: GetSalesPrice
        params:
          - name: parItemNo
            dto-name: itemNo
          - name: parVariantCode
            dto-name: variantCode
          - name: parSalesCode
            dto-name: salesCode
          - name: parPriceDate
            dto-name: priceDate
    domain: BYL.LOCAL
    password: '{cipher}82da2fbd64b312078b6fe5c37b9c686f61ca2a7c5b8dd5a804bc3b49b1dced19'
    prefix: wss
    schema: WSMarketplace
    url: http://svmos101037-nas.byl.local:7047/CENTRAL/WS/BIMBA%20Y%20LOLA/Codeunit/WSMarketplace
    user: srvcplmnavdes
    workstation: LOCALHOST

byl:
  audit:
    enabled: false
    internal-enable: false
  ldap:
    active: false
  code-unit:
    enabled: true
    retry:
      delay: 1000
      max-attempts: 3
      max-delay: 5000

cache:
  enable-redis: true

spring:
  profiles:
    active: ${SHORT_ENV}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  # Datasources
  datasource:
    datasource-initializer-enabled: false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: jdbc:sqlserver://svmos101036-sql.byl.local;databaseName=NAVWEB;sslProtocol=TLSv1.2;trustServerCertificate=true;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    poolName: HikariCP-Principal
    username: uapimasterproduct
    password: '{cipher}dfdb5079a2f5d88ff02d3be2264b1cb1708a56aa29b530e815c3cf2ce760db522892bfd5a014d8007bc475fe60c6eb24'

webclient:
  max-in-memory-size: 10000000
  plm:
    base-path: ${services.distribucion.interna.gateway-plm-api-v1}
    retry-attempts: 3
    retry-time: 30
    endpoints:
      shipment-orders-galgo: /shipment-orders/galgo