app:
  fqdn: localhost

byl:
  audit:
    enabled: false
    internal-enable: false
  ldap:
    active: false
  addTraceInApiException: true
  isRestAuditable: true
  excludeAuditRest: ''

cache:
  enable-redis: false

spring:
  profiles:
    active: ${SHORT_ENV},jar
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  # Datasources
  datasource:
    datasource-initializer-enabled: false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: jdbc:sqlserver://svmos101036-sql.byl.local;databaseName=NAVWEB;sslProtocol=TLSv1.2;trustServerCertificate=true;
    username: uomsdev
    password: '{cipher}47b50a89a885ad24ef46595a55cd5c88c6b874aae4f06e003b8137486bfbeeec'
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    poolName: HikariCP-Principal

codeunit:
  user: srvcnavparserdev
  password: 70wQw8nLOiUBIdt14sTns4bwPT86AJ


azure:
  storage:
    accounts:
      global-persistence:
        account-name: globalpersistence
        account-key: '{cipher}633140e53ebeb3f501200f518c6904ba30e33d829f971c9ad9e12f732bdfad3ed00831f2a9abdc7feeec3805b33787f3cf2aa80b04e0ed0c94beb7123ab458491e2e071355328fb1035095f435d082858b6f872127982c9788fbc0e38d1c8a797130ea2b15ff13a907269d9f8bc95970'
        tables:
          order-queue-audit: DevOmsSynchOrders
      core-data:
        account-name: coredatabyldev
        account-key: '{cipher}ae88f46b87c3d2b0a37c496016e061f0a25112fa992bf7e97d899d91d86c5e98378b852112dc3642e37d10210e88795c63985298176a94bc823ccc3c1321d477193c9916a5308fdceb6a516418e81faee913f36c2df50a396e971374d38cbd84a9cef0531865bd72a45f06daa532bf51'
        tables:
          product-images: images
        blobs:
          product-images: images
