app:
  label-style-image: PRINCIPAL

azure:
  consumer:
    enabled: false
  producer:
    enabled: false
  storage:
    enabled: false

byl:
  audit:
    enabled: false
    internal-enable: false
  auto-health: false
  datasource-primary:
    enabled: false
  encryption:
    enabled: true
    private: '{cipher}540423e80bc80be33e02d144505e3c27340ec1eea67c0e747d89871a5cdf0269fa716f60b8817492135e2718868472f2f601d928522d47fad63e8f07170d98984e5094313e151f8281c230387d112ff8aee6447a510ee30dc824421a6a99263737a6ebdad690d13572de6ab760c15cd4e24991cfd8eebc9b4e4fe3110fb3e05a35c0b933d196702cf7204f87db0f5b4ca06e11f422410536260f662ebb4e6016a2e66fdd8fe0efb541242277dfc304c40b6c0dc99cfa6a09d16ca9c030ad3be4970a7c9c5eb817427f56bd8e6bf30cff05d93a46a6079e33b97850ec38901c9a14a239051c887e8627b8f1c0a251c8da2b17e74804e7f7b216a20e68f241a1e99f975ffacd3c07c061f55d9ac05ed21c6071e070a668a1536a18ffdb0da54eb1f6fc0ea4aa958a62ca479425db07b957c515486610e17968cb28c0f4dfb53619cc236936f6dad50d1feba3af134cef1c526b787a4d921fd2c3f29f1695869c5fe6a8e6b02c6d39abb2cee868c2b64fde2700fc84e68b340201a63b622f68df782d398d930a1e6849b46992911f85cd1d0c2d8dc8742b6f8a66b29980cdf70dcf0164b6a638690ca819e35f07f9f367d08f04f1996eb7e44c72fcbb2546fd0f5ede58f8a473ed3c617d0ad9e7a4213400352135bf5614b13a57b365972cb76177eeb0fab8bb87e30d0bd0ac18da196873e5a7efb9c901d9d0ec9a3b864cb752d68c2881a007f8d840bac32e82a8f97189dc588bd046ccb4c78035e5b7419bdca1ac66fb6c0db40202759696169d075585'
    public: '{cipher}f27aeec445035e71a89385db8c951a07ec56085ccceed29f80fb484240c18916d7f686f0edb97d2c21d86002752f780d4f351841e8eee2208d0961e39346c23b75ba8ab30455323819e8546dabbcf383da151d0d7df8793824550ad53555e1851b643717c7220be8c1c556b6ef9dddf0e6611383d8cb8f625af8f269569f5600b668bbc8ef15e585b85aabb3bf0fb8ab0e87ab03a49b395d0e3a3192e3a8cf3ab40cf3503af353fb271cfa519fd44a7d'
  ldap:
    active: false

cache:
  enable-redis: true
  caches-ttl:
    cache-day: 86400
    findCountryById: 86400

info:
  app:
    name: Gateway api PLM - TaskForce Producto (ByL)
    description: Aplicación para gestionar las llamadas a la api de PLM
    version: ${project.version:0.0.0}

plm-config:
  enabled: true
  base-url: https://bimba-preprod.centricsoftware.com
  base-path: /csi-requesthandler/api/v2
  centric-login: /session
  user: Administrator
  password: '{cipher}9115c6ec1dc04f938caf129f44f5a614cc775c2094b85d335b9d3ff6d4b034604ca11fe805ba69538e63c999e5c99c0d'
  timeout: 5
  retry:
    login: 3
    login-interval: 2000
    get: 3
    get-interval: 2000

server:
  shutdown: graceful
spring:
  datasource:
    datasource-initializer-enabled: false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: jdbc:mysql://192.168.52.66;databaseName=C8;trustServerCertificate=true
    username: shadowuser
    password: '{cipher}aefed2a74ecee0121f80903e235ab1e26076f09d261638513e69b4ad2ef9bea0'
    driverClassName: com.mysql.cj.jdbc.Driver
    poolName: HikariCP-Principal
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: ${SHORT_ENV}

webclient:
  plm:
    limit: 50
    services:
      bom: /apparel_boms/{id}
      bom-revision: /apparel_bom_revisions/{id}
      care-and-compositions: /care_and_compositions
      care-and-compositions-id: /care_and_compositions/{id}
      care-and-compositions-revision-id: /care_and_composition_revisions/{id}
      care-symbol-id: /care_symbols/{id}
      category: /category1s/{id}
      colorway: /colorways/{id}
      colorways: /colorways
      compositions-id: /compositions/{id}
      contact: /contacts/{id}
      country: /countries/{id}
      enum-lists: /enum_lists
      enum-values: /enum_values
      enum-values-id: /enum_values/{id}
      factory: /factories/{id}
      factories: /factories
      contact-by-id: /contacts/{id}
      country-by-id: /countries/{id}
      imageById: /images/{id}
      lookup-item: /lookup_items/{id}
      lookup-items: /lookup_items
      lookup-items-subtype: /lookup_item_subtypes/{id}
      lookup-items-subtypes: /lookup_item_subtypes
      material: /materials/{id}
      material-composition-id: /material_compositions/{id}
      material-types: /material_types
      order: /orders/{id}
      part-material: /part_materials/{id}
      print-design-color: /print_design_colors/{id}
      print-design-colors: /print_design_colors
      purchase-order: /purchase_orders/{id}
      purchase-orders: /purchase_orders
      season: /seasons/{id}
      seasons: /seasons
      shipment: /shipments/{id}
      shipments: /shipments
      shipment-terms: /shipment_terms
      shipping-port: /shipping_ports/{id}
      size: /product_sizes/{id}
      sizes: /product_sizes
      size-range: /size_ranges/{id}
      size-ranges: /size_ranges
      sku: /skus/{id}
      skus: /skus
      style: /styles/{id}
      styles: /styles
      subfamily-ids: /lookup_items
      supplier: /suppliers/{id}
      suppliers: /suppliers
      supplier-revision: /supplier_item_revisions/{id}
      transfer-lookup-item: /lookup-items/transfer/{id}
      user: /users/{id}
