app:
  config:
    memory-cache:
      locations-ttl: 3600
      lock-config-ttl: 120
    block-size:
      save-locks: 500

azure:
  sb:
    topics:
      galgo-assortments:
        keyName: galgo-assortments
        key: '{cipher}0344ef0e75908f0cc17170d9ff70cdcff20e8cdc20edd40b8d3ab4c6fd6b58522543ddfe9cbad8a38167f89db54634a80478889b8e7efb18f5594971f30ac1bf'
        topic: distribucion.galgo-assortments

byl:
  audit:
    enabled: false
    internal-enable: false

cache:
  enable-redis: false

server:
  servlet:
    context-path: "/${spring.application.name}-consumer-v${app.version_url}"

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    azure:
      servicebus:
        bindings:
          consumeChanges-in-0:
            group: changes.Galgo
        connection-string: Endpoint=${azure.sb.endpoint};SharedAccessKeyName=${azure.sb.topics.galgo-assortments.keyName};SharedAccessKey=${azure.sb.topics.galgo-assortments.key};EntityPath=${azure.sb.topics.galgo-assortments.topic}
        enabled: true
    stream:
      bindings:
        consumeChanges-in-0:
          destination: distribucion.galgo-assortments
          group: changes.Galgo
        consumeTopStore-in-0:
          destination: distribucion.galgo-assortments
          group: top-store.Central
        consumeLocks-in-0:
          destination: distribucion.galgo-assortments
          group: locks.Central
      default:
        consumer:
          maxAttempts: 4
      function:
        definition: consumeChanges; consumeTopStore; consumeLocks;
      servicebus:
        bindings:
          consumeChanges-in-0:
            consumer:
              auto-bind-dlq: true
              auto-complete: false
              checkpoint-mode: MANUAL
              max-auto-lock-renew-duration: 6m
              max-concurrent-calls: 1
              max-concurrent-sessions: null
              prefetch-count: 1
              receive-mode: PEEK_LOCK
              requeue-rejected: true
              session-enabled: null
          consumeTopStore-in-0:
            consumer:
              auto-bind-dlq: true
              auto-complete: false
              checkpoint-mode: MANUAL
              max-auto-lock-renew-duration: 2m
              max-concurrent-calls: 1
              max-concurrent-sessions: null
              prefetch-count: 1
              receive-mode: PEEK_LOCK
              requeue-rejected: true
              session-enabled: null
          consumeLocks-in-0:
            consumer:
              auto-bind-dlq: true
              auto-complete: false
              checkpoint-mode: MANUAL
              max-auto-lock-renew-duration: 2m
              max-concurrent-calls: 1
              max-concurrent-sessions: null
              prefetch-count: 1
              receive-mode: PEEK_LOCK
              requeue-rejected: true
              session-enabled: null
  profiles:
    active: ${SHORT_ENV}

webclient:
  max-in-memory-size: 10000000
  timeout-seconds: 120
  gateway-distribucion:
    base-path: ${services.distribucion.interna.gateway-distribucion-api-v1}
    endpoints:
      ref-sizes-item-no: /references/sizes
      locks-erp-save: /assortments/ref-locks
      top-store-erp-save: /assortments/top-store
    retry-attempts: 1
    retry-time: 5
  galgo-back:
    base-path: ${services.distribucion.interna.galgo-back-api-v1}
    #base-path: http://localhost:8081/galgo-back-api-v1
    endpoints:
      assortments-locations: /locations/assortments
      ref-locks-config: /ref-locks/config
      ref-locks-location: /ref-locks/global
      ref-locks-reference: /ref-locks/global/{reference}
      ref-locks-save: /ref-locks/global
      top-ref-detail: /top-references/search/master/detail
      top-ref-entries: /top-references/entries/search/master
    retry-attempts: 1
    retry-time: 5
