byl:
  audit:
    enabled: false
    internal-enable: false

cache:
  enable-redis: false

spring:
  profiles:
    active: ${SHORT_ENV}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

webclient:
  max-in-memory-size: 10000000
  retry-attemps: 3
  retry-time: 10
  supply-chain:
    auth:
      user: 'BYLOMSARQ'
      pass: '{cipher}a8ae4b090b250f2b826f84f6f06e76a2a99f0341cd787f34a91fb6308eba4694538bcfc953af33ca0d41d68b8083b63b'
    base-path: https://bylla-prod-1.oms.supply-chain.ibm.com/smcfs/restapi
    endpoints:
      create-order: /executeFlow/ByLOrderCreationInSyncService
      get-page: /invoke/getPage
      multi-api: /invoke/multiApi
  timeout-seconds: 10
  watson-commerce:
    auth:
      client-id: rBFOD96rZuaOyOjobXI316LWGZD0V6Xg
      client-secret: '{cipher}4bdbb0671613bd3c762c210d3c6879164635e5802b062a07d6f1836302cb019e15cd35e294ba81023c84e53b319cd2981b750886ed4a066eab352fdf63afdabb'
    tenant: '{cipher}ccd07028fabd6669dfc566e1b74b554d1ff40c64b5c400fb656468c5ecde2a90'
    inventory:
      base-path: https://api.watsoncommerce.ibm.com/inventory/${webclient.watson-commerce.tenant}
      endpoints:
        availability-network: /v2/availability/network
        availability-node: /v2/availability/node
        job-info: /v1/jobs/{jobId}
        job-trigger: /v2/configuration/events/dgAvailabilitySnapshot.v2/publish_all
        oauth: /v1/oauth2/token
        reservations: /v2/reservations
    catalog:
      base-path: https://api.watsoncommerce.ibm.com/catalog/${webclient.watson-commerce.tenant}
      endpoints:
        items: /v1/items