server:
  port: 8081

command:
  name: configuracionComandos
  commands:
    - name: SYNC_REFERENCE_PRICE
      bean-name: syncReferencePriceCommand

spring:
  profiles:
    active: ${SHORT_ENV}

plm-config:
  enabled: true
  base-path: https://bimba-preprod.centricsoftware.com/csi-requesthandler/api/v2
  centric-login: /session
  user: Administrator
  password: '{cipher}9115c6ec1dc04f938caf129f44f5a614cc775c2094b85d335b9d3ff6d4b034604ca11fe805ba69538e63c999e5c99c0d'

process:
  config:
    execute-plm-changes: false
    retry-attempts: 3
    mail:
      host: correoweb.bimbaylola.com
      port: 587
      username: srvcmailsml@bimbaylola.com
      password: '{cipher}8961f6abd28d3ad1dd88c1561b7c247961989c18b3c212f29eefa62e693908d338ec393231cd0531240a42efcffa815f'
      from: srvcmailsml@bimbaylola.com
      to: ahathat@atsistemas.com, psantiago@atsistemas.com
      cc: ahathat@atsistemas.com, psantiago@atsistemas.com
      errors: psantiago@atsistemas.com

webclient:
  max-in-memory-size: 10000000
  retry-attemps: 3
  retry-time: 10
  plm:
    limit: 50
    services:
      colorways: /colorways
      colorways-id: /colorways/{id}
  producto:
    page-size: 500
    ##base-path: http://desazure.byl.local/gateway-product-api-v1
    base-path: http://localhost:8080/gateway-product-api-v1
    services:
      reference-price: /plm/reference-price


      
      