azure:
  storage:
    enabled: false
    accounts:
      distribucion:
        account-id: distribucion
        tables:
          replenishment-config: ReplenishmentConfig
          replenishment-audit: ReplenishmentAudit
          batch-status: BatchStatus
    config:
      accounts:
        distribucion:
          name: tskfdistribuciondev
          key: '{cipher}55d62789a2981eedb4eb0959bb97cf5844ee24e9b21f076ab2ba7609a6af940b0c6d0696fdc5a14f51ec21e9ba6766757bf3e1cca4b8d5c97e7370f103f6b49b88e90cf54238ba4a4ad48a4bc5d96c1643dc2995d5db92071677d2d84f83e07213b0c27eccc2080ee7354f974d1867ba'

byl:
  mail:
    enabled: true

command:
  name: configuracionComandos
  commands:
    - name: PLANNED
      bean-name: plannedReplenishmentCommand
    - name: ONDEMAND
      bean-name: onDemandReplenishmentCommand
    - name: CLEAN
      bean-name: cleanAuditCommand
    - name: UNLOCK
      bean-name: unlockExecutionCommand

mail:
  generate-file: false

process:
  config:
    audit:
      execution-keep-days: 30
      config-keep-days: 30
    wait-time: 60
    wait-on-demand-messages-time: 60
    dependencies:
      PLANNED:
        - batch: oms-replenishment
          command: ONDEMAND
          action: WAIT
      ONDEMAND:
        - batch: oms-replenishment
          command: PLANNED
          action: CANCEL
    erp-process:
      message-sleep-time: 2
      close-pending-orders-timeout: 30
      create-transfer-orders-timeout: 30
      retry-attempts: 2
      retry-attempts-blocked: 5
      retry-sleep-time: 0

spring:
  cloud:
    azure:
      servicebus:
        bindings:
          consumeOnDemand-in-0:
            group: onDemandReplenishment
          consumeStatus-in-0:
            group: statusReplenishment
        connection-string: '{cipher}5b333706b3c69878bf15d03a17053e2e1e31406aaa41b096acbb10fa89bdc094fbfab134f4b65498cd6adef389a59a95749b06a969ddc67d553ec4bcf997144147fe2950b15c564acab5e153199d7fcd4116010bd0efa0ee9dfa07ef6594d06467c73b518bd9b4d9cb855d7c5ac64cf12fcce48e6bffcbcfd7e8e8d958d2e58d086c148da38d751c4d780b632797a86bceebd9ed0527640503c8353da2b50f513529b4ea2d84d9bb120174829aef1c75de06b427f7af72759175566a3c8b6810'
        enabled: true
    stream:
      bindings:
        consumeOnDemand-in-0:
          destination: distribucion.oms-erp
          group: onDemandReplenishment
        consumeStatus-in-0:
          destination: distribucion.oms-erp
          group: statusReplenishment
      default:
        consumer:
          maxAttempts: 4
      function:
        definition: consumeOnDemand; consumeStatus;
      servicebus:
        bindings:
          consumeOnDemand-in-0:
            consumer:
              auto-bind-dlq: true
              auto-complete: false
              checkpoint-mode: MANUAL
              max-auto-lock-renew-duration: 2m
              max-concurrent-calls: 1
              max-concurrent-sessions: null
              prefetch-count: 1
              receive-mode: PEEK_LOCK
              requeue-rejected: true
              session-enabled: null
          consumeStatus-in-0:
            consumer:
              auto-bind-dlq: true
              auto-complete: false
              checkpoint-mode: MANUAL
              max-auto-lock-renew-duration: 2m
              max-concurrent-calls: 1
              max-concurrent-sessions: null
              prefetch-count: 1
              receive-mode: PEEK_LOCK
              requeue-rejected: true
              session-enabled: null

webclient:
  max-in-memory-size: 20000000
  distribucion:
    page-size: 50000
    update-size: 10000
    query-size: 500
    retry-attemps: 1
    retry-time: 1
    base-path: ${services.distribucion.interna.gateway-distribucion-api-v1}
    services:
      items-to-replenish: /replenishment/items-to-replenish
      available-stock: /replenishment/available
      save-proposal: /replenishment/proposal
      clear-proposal: /replenishment/proposal
      erp-process: /replenishment/abc/erp-process/{processName}
      scale-warehouses: /replenishment/scale-warehouses
  galgo:
    page-size: 500
    retry-attemps: 5
    retry-time: 30
    base-path: ${services.distribucion.interna.galgo-back-api-v1}
    services:
      get-replenishment-config: /replenishment/config/{id}
      get-all-replenishment-config: /replenishment/config