spring:
  port: 8081
  profiles:
    active: ${SHORT_ENV}
  
process:
  config:
    distribucion-page-size: 50000
    supplies-page-size: 100
    persistence-file-path: /mnt/persistent/${spring.application.name}
    persistence-max-records: 5
    inventory-params:
      region-code: ES
    log-inventory-data: true
    
webclient:
  max-in-memory-size: 10000000
  distribucion:
    base-path: 'http://localhost:8080/gateway-distribucion-api-v1'
    #base-path: http://desazure.byl.local/gateway-distribucion-api-v1
    services:
      syncro-adjustment: /inventory/syncro/adjustment
      syncro-shipment: /inventory/syncro/shipment
      syncro-sale: /inventory/syncro/reservation
      full-inventory: /inventory/syncro/full
      max-references: /inventory/maxReferences
  oms:
    tenant: '{cipher}83d89f69899cc742fef51bb36e1561856f2195af82f5c16493b8c999464ffd6c'
    oauth:
      client-id: '{cipher}9f648580f8bf05b29bad159e6b118417ed03cd0d2ed6f2a97edcbeab6b34a28bcbc65d79664b5132fae8d25c8a41306825084da72d3672f5c3513e3890a32cff'
      client-secret: '{cipher}58025dc0788227423810cfc69e3a749ae604548378eaab6efcf4c1b57f8340d97cbdb9b53f4fc384cd9f90176c5ce94dce8f608a39ede094ddf64b813bbbf118'
    base-path: https://api.watsoncommerce.ibm.com/inventory/${webclient.oms.tenant}/v1
    services:
      supplies: /supplies
      oauth: /oauth2/token
      ship-nodes: /configuration/shipNodes