command:
  name: configuracionComandos
  commands:
    - name: SYNCH_INVENTORY_FULL
      bean-name: fullInventoryCommand
    - name: SYNCH_INVENTORY
      bean-name: incrementalInventoryCommand
    - name: UNLOCK_EXECUTION
      bean-name: unlockExecutionCommand

spring:
  profiles:
    active: ${SHORT_ENV}

process:
  config:
    distribucion-page-size: 50000
    supplies-page-size: 100
    log-inventory-data: true
    single-season: false
    dependencies:
      SYNCH_INVENTORY_FULL:
        - batch: oms-inventory
          command: SYNCH_INVENTORY
          action: WAIT
      SYNCH_INVENTORY:
        - batch: oms-inventory
          command: SYNCH_INVENTORY_FULL
          action: CANCEL

webclient:
  max-in-memory-size: 10000000
  distribucion:
    retry-attemps: 7
    retry-time: 60
    base-path: http://desazure.byl.local/gateway-distribucion-api-v1
    services:
      syncro-adjustment: /inventory/syncro/adjustment
      syncro-shipment: /inventory/syncro/shipment
      syncro-sale: /inventory/syncro/reservation
      full-inventory: /inventory/syncro/full
      max-references: /inventory/maxReferences
      active-seasons: /inventory/active-seasons
  oms:
    retry-attemps: 5
    retry-time: 10
    tenant: '{cipher}83d89f69899cc742fef51bb36e1561856f2195af82f5c16493b8c999464ffd6c'
    oauth:
      client-id: '{cipher}9f648580f8bf05b29bad159e6b118417ed03cd0d2ed6f2a97edcbeab6b34a28bcbc65d79664b5132fae8d25c8a41306825084da72d3672f5c3513e3890a32cff'
      client-secret: '{cipher}58025dc0788227423810cfc69e3a749ae604548378eaab6efcf4c1b57f8340d97cbdb9b53f4fc384cd9f90176c5ce94dce8f608a39ede094ddf64b813bbbf118'
    base-path: https://api.watsoncommerce.ibm.com/inventory/${webclient.oms.tenant}/v1
    services:
      supplies: /supplies
      oauth: /oauth2/token
      ship-nodes: /configuration/shipNodes

azure:
  storage:
    enabled: false
    accounts:
      distribucion:
        account-id: distribucion
        tables:
          sync-references: SyncReferences
          batch-status: BatchStatus
    config:
      accounts:
        distribucion:
          name: tskfdistribuciondev
          key: 20XF+PYutl64nWLO3Rgh3tgN6NQhIlHOUrXccA/E5/8GWWBAWfpWVA00hgLBvxaVTeUJ55o8vqQb+AStMYqLxA==