command:
  name: configuracionComandos
  commands:
    - name: SYNCH_ORDER_STATUS
      bean-name: synchOrderStatusCommand

process:
  config:
    distribucion-page-size: 500
    dependencies:
      SYNCH_INVENTORY_FULL:
        - batch: oms-inventory
          command: SYNCH_INVENTORY
          action: CANCEL

spring:
  profiles:
    active: ${SHORT_ENV}

webclient:
  max-in-memory-size: 10000000
  distribucion:
    base-path: http://desazure.byl.local/gateway-distribucion-api-v1
    services:
      synch-order-status: /order/synch/status
      max-references: /inventory/maxReferences


project:
  mq:
    host: 'bylla-dev-1-mq.oms.supply-chain.ibm.com'
    port: 15443
    queue-manager: OM_QMGR
    channel: SYSTEM.TLS.SVRCONN
    receive-timeout: 20000
    cypher: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    queue:
      confirm-shipment-in: BYL_CONFIRM_SHIPMENT_IN

azure:
  storage:
    enabled: false
    accounts:
      distribucion:
        account-id: distribucion
        tables:
          sync-references: SyncReferences
          batch-status: BatchStatus
    config:
      accounts:
        distribucion:
          name: tskfdistribuciondev
          key: 20XF+PYutl64nWLO3Rgh3tgN6NQhIlHOUrXccA/E5/8GWWBAWfpWVA00hgLBvxaVTeUJ55o8vqQb+AStMYqLxA==
