azure:
  sb:
    topics:
      distribucion-ecommerce:
        keyName: distribucion-ecommerce
        key: '{cipher}d7cfcc71ccdd5b926de9d6e7ef62aa2fe6980632901d316bc64bf29601d9d4036951cf7c980003f7683d91327d21f8ce98a240554549c7abc83933e721c1d7d9'
        topic: distribucion.ecommerce
      service-to-central:
        keyName: service-to-central
        key: '{cipher}4a140473c34cc1e9958b2cf80379a7cf7efb7ae27fef6deffbaffb823b4d4d49d3b5d830aa57c2ece48e949abdfe9dd4a26ea0a94e5fbca60b7c667503726da8'
        topic: distribucion.service-to-central

byl:
  audit:
    enabled: false
    internal-enable: false

cache:
  enable-redis: false

server:
  servlet:
    context-path: "/${spring.application.name}-consumer-v${app.version_url}"

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    azure:
      servicebus:
        bindings:
          consumeCreateOrder-in-0:
            group: createOrder.Central
          consumeCreateReturnOrder-in-0:
            group: createReturn.Central
          consumeCreateManualReturnOrder-in-0:
            group: createManualReturn.Central
        connection-string: Endpoint=${azure.sb.endpoint};SharedAccessKeyName=${azure.sb.topics.distribucion-ecommerce.keyName};SharedAccessKey=${azure.sb.topics.distribucion-ecommerce.key};EntityPath=${azure.sb.topics.distribucion-ecommerce.topic}
        enabled: true
    function:
      definition: consumeCreateOrder; consumeCreateReturnOrder; consumeCreateManualReturnOrder; consumeServiceToCentral; consumeConfirmShipment;
    stream:
      binders:
        service-to-central:
          type: servicebus
          defaultCandidate: false
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: Endpoint=${azure.sb.endpoint};SharedAccessKeyName=${azure.sb.topics.service-to-central.keyName};SharedAccessKey=${azure.sb.topics.service-to-central.key};EntityPath=${azure.sb.topics.service-to-central.topic}
      bindings:
        consumeCreateOrder-in-0:
          destination: ${azure.sb.topics.ecommerce.topic}
          group: createOrder.Central
        consumeCreateReturnOrder-in-0:
          destination: ${azure.sb.topics.ecommerce.topic}
          group: createReturn.Central
        consumeCreateManualReturnOrder-in-0:
          destination: ${azure.sb.topics.ecommerce.topic}
          group: createManualReturn.Central
        consumeCreateOrderNav-in-0:
          destination: ${azure.sb.topics.service-to-central.topic}
          group: createOrder.Nav
          binder: service-to-central
        consumeCreateOrderCentralFo-in-0:
          destination: ${azure.sb.topics.service-to-central.topic}
          group: createOrder.centralfo
          binder: service-to-central
        consumeConfirmShipment-in-0:
          destination: ${azure.sb.topics.service-to-central.topic}
          group: confirmShipment.Nav
          binder: service-to-central
      default:
        consumer:
          maxAttempts: 4
      servicebus:
        bindings:
          consumeCreateOrder-in-0:
            consumer:
              auto-bind-dlq: true
              auto-complete: false
              checkpoint-mode: MANUAL
              max-auto-lock-renew-duration: 2m
              max-concurrent-calls: 1
              max-concurrent-sessions: null
              prefetch-count: 10
              receive-mode: PEEK_LOCK
              requeue-rejected: true
              session-enabled: null
          consumeCreateReturnOrder-in-0:
            consumer:
              auto-bind-dlq: true
              auto-complete: false
              checkpoint-mode: MANUAL
              max-auto-lock-renew-duration: 2m
              max-concurrent-calls: 1
              max-concurrent-sessions: null
              prefetch-count: 10
              receive-mode: PEEK_LOCK
              requeue-rejected: true
              session-enabled: null
          consumeCreateManualReturnOrder-in-0:
            consumer:
              auto-bind-dlq: true
              auto-complete: false
              checkpoint-mode: MANUAL
              max-auto-lock-renew-duration: 2m
              max-concurrent-calls: 1
              max-concurrent-sessions: null
              prefetch-count: 10
              receive-mode: PEEK_LOCK
              requeue-rejected: true
              session-enabled: null
          consumeCreateOrderNav-in-0:
            consumer:
              auto-bind-dlq: true
              auto-complete: false
              checkpoint-mode: MANUAL
              max-auto-lock-renew-duration: 2m
              max-concurrent-calls: 1
              max-concurrent-sessions: null
              prefetch-count: 10
              receive-mode: PEEK_LOCK
              requeue-rejected: true
              session-enabled: null
          consumeCreateOrderCentralFo-in-0:
            consumer:
              auto-bind-dlq: true
              auto-complete: false
              checkpoint-mode: MANUAL
              max-auto-lock-renew-duration: 2m
              max-concurrent-calls: 1
              max-concurrent-sessions: null
              prefetch-count: 10
              receive-mode: PEEK_LOCK
              requeue-rejected: true
              session-enabled: null
          consumeConfirmShipment-in-0:
            consumer:
              auto-bind-dlq: true
              auto-complete: false
              checkpoint-mode: MANUAL
              max-auto-lock-renew-duration: 2m
              max-concurrent-calls: 1
              max-concurrent-sessions: null
              prefetch-count: 10
              receive-mode: PEEK_LOCK
              requeue-rejected: true
              session-enabled: null
  profiles:
    active: ${SHORT_ENV}

webclient:
  max-in-memory-size: 10000000
  gateway-distribucion:
    base-path: ${services.distribucion.interna.gateway-distribucion-api-v1}
    endpoints:
      create-return-order: /order/return/create
      create-manual-return-order: /order/manual-return/create
      create-order: /order/create
      confirm-shipment: /order/confirm-shipment
    retry-attempts: 3
    retry-time: 10
  gateway-oms:
    base-path: ${services.distribucion.interna.gateway-oms-api-v1}
    endpoints:
      create-order: /orders
    retry-attempts: 3
    retry-time: 10
