app:
  fqdn: localhost

byl:
  audit:
    enabled: false
    internal-enable: false
  ldap:
    active: false

cache:
  enable-redis: true

azure:
  storage:
    enabled: false
    accounts:
      tiendas:
        account-id: tskf_tiendas
        tables:
          mapping-behaviour: clickCollectApiMappingBehaviour
    config:
      accounts:
        tskf_tiendas:
          name: tskftiendasdev
          key: '{cipher}f743bdbb61298816e331fc863b103d9be92efb064ae20d38a3ab665d36265a8f3d3fc976e2854baab4f0bd25a51028ecf66bf8d742e7c2a0d17616387e3886bd48e4eb90ced25e0152d3f541090fb99edd64b232b2f7536ff62a8e9b1a83b1fb5fb2c2e23f99ccad6fc06f5aa07904c5'
spring:
  profiles:
    active: ${SHORT_ENV}

  # Datasources
  datasource:
    datasource-initializer-enabled: false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: jdbc:sqlserver://svmos101036-sql.byl.local;databaseName=NAVWEB;sslProtocol=TLSv1.2;trustServerCertificate=true;
    username: uapiclickandcollect
    password: '{cipher}69e46e66f96ec41a9d108c673bc6abca3c7c3a69bde539fd34c55377696e9e484894f2338c791a3be9ef136af359de7c64445943a71b670c80d9f36b9690eff5'
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    poolName: HikariCP-Principal

springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha

elasticsearch:
  log-level: INFO

controller:
  max-pagesize: 100