app:
  fqdn: localhost

byl:
  audit:
    enabled: false
    internal-enable: false
  ldap:
    active: false
  addTraceInApiException: true
  isRestAuditable: true
  excludeAuditRest: ''

cache:
  enable-redis: false

services:
  oms:
    user: BYLOMS
    pass: '{cipher}4252f0a81fcb5ffac30e7a9ae905495b23dff623acaa142e2bd8ee9f5b342d32'
    base-path: https://bylla-dev-1.oms.supply-chain.ibm.com/smcfs/restapi/executeFlow
    endpoints:
      create-order: /ByLOrderCreationInSyncService

spring:
  profiles:
    active: ${SHORT_ENV},jar
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  # Datasources
  datasource:
    datasource-initializer-enabled: false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    url: jdbc:sqlserver://svmos101036-sql.byl.local;databaseName=NAVWEB;sslProtocol=TLSv1.2;trustServerCertificate=true;
    username: uomsdev
    password: '{cipher}47b50a89a885ad24ef46595a55cd5c88c6b874aae4f06e003b8137486bfbeeec'
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    poolName: HikariCP-Principal

project:
  mq:
    host: 'bylla-dev-1-mq.oms.supply-chain.ibm.com'
    port: 15443
    queue-manager: OM_QMGR
    channel: SYSTEM.TLS.SVRCONN
    receive-timeout: 20000
    cypher: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    queue:
      create-order: BYL_DOM_OUT_RELEASE
      confirm-shipment: BYL_STORE_CONFIRM_SHIP_OUT